import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Disclaimer for DataForge — generated data is fictional and tools are provided for testing and education.",
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <article className="mx-auto max-w-2xl py-8 [&_h2]:mt-8 [&_h2]:text-xl [&_h2]:font-bold [&_p]:mt-2 [&_p]:text-muted">
      <h1 className="text-3xl font-extrabold tracking-tight">Disclaimer</h1>
      <p className="mt-4">Last updated: {new Date().getFullYear()}</p>

      <h2>Fictional data</h2>
      <p>
        All identifiers, addresses, card numbers, wallet strings and other values generated by
        DataForge are <strong>fictional</strong> and intended solely for software testing, demos and
        education. They do not correspond to real people, accounts or financial instruments and must
        not be used for fraud or impersonation.
      </p>

      <h2>Accuracy</h2>
      <p>
        We strive for correctness, but tool outputs (conversions, calculations, formula results, etc.)
        are provided without guarantee. Always verify critical results independently.
      </p>

      <h2>Your responsibility</h2>
      <p>
        You are responsible for how you use the tools and any files you process. Do not upload or
        process content you are not authorized to handle. Files are processed locally in your browser.
      </p>

      <h2>Third-party data</h2>
      <p>
        Live data (e.g. cryptocurrency prices, DNS/IP lookups) comes from third-party providers and may
        be delayed or inaccurate. It is informational only and not financial advice.
      </p>

      <h2>Contact</h2>
      <p>
        Email <a href="mailto:contact@zestcommerce.in" className="text-brand-600 underline">contact@zestcommerce.in</a>.
      </p>
    </article>
  );
}
